export function createAssetPanelProps(state) {
  return {
    assetGroup: state.assetGroup,
    setAssetGroup: state.setAssetGroup,
    showAssetKindMenu: state.showAssetKindMenu,
    setShowAssetKindMenu: state.setShowAssetKindMenu,
    showAssetPreviews: state.showAssetPreviews,
    setShowAssetPreviews: state.setShowAssetPreviews,
    assets: state.assets,
    selectedAssetId: state.selectedAssetId,
    selectedAsset: state.selectedAsset,
    selectAsset: state.selectAsset,
    tokens: state.tokens,
    objects: state.objects,
    creatorOpen: state.creatorOpen,
    creatorKind: state.creatorKind,
    editingAsset: state.editingAsset,
    openCreator: state.openCreator,
    setCreatorOpen: state.setCreatorOpen,
    setEditingAsset: state.setEditingAsset,
    handleCreatorCreate: state.handleCreatorCreate,
    updateAssetById: state.updateAssetById,
    reorderAssets: state.reorderAssets,
    setAssets: state.setAssets,
    setSelectedAssetId: state.setSelectedAssetId,
    alertFn: (message) => state.showToast(message, "warning", 3500),
    confirmFn: (message) => state.confirmUser(message),
  };
}
