import { useCallback } from "react";
import {
  saveProject as saveProjectManager,
  saveProjectAs as saveProjectAsManager,
  loadProjectById,
  listMaps,
  deleteMap,
  loadAssetsFromStoredParent,
  isAssetsFolderConfigured,
  hasCurrentProjectDir,
} from "../../../../../application/save-load/index.js";
import { useLegacyAssetWorkflow } from "../../state/useLegacyAssetWorkflow.js";
import { useLegacyHistory } from "../../state/useLegacyHistory.js";
import { useSelectionSettingsPersistence } from "../../state/useSelectionSettingsPersistence.js";
import { useLegacyProjectLoading } from "../../../modules/save-load/useLegacyProjectLoading.js";
import { useLegacyProjectSaving } from "../../../modules/save-load/useLegacyProjectSaving.js";

export function useLegacyProjectModules({
  projectNameRef,
  layerState,
  sceneState,
  gridSettingsState,
  gridSelectionState,
  tokenSelectionState,
  canvasRefsState,
  layoutRefs,
  tileState,
  setTileSize,
  undoRedoState,
  feedbackState,
  promptUser,
  confirmUser,
  zoomState,
  layerVisibilityState,
  layerList,
  showGridLines,
  engine,
  setEngine,
  canvasDisplayState,
}) {
  const legacyAssetWorkflow = useLegacyAssetWorkflow({
    hasSelection: gridSelectionState.hasSelection,
    selectedObj: gridSelectionState.selectedObj,
    selectedObjsList: gridSelectionState.selectedObjsList,
    clearObjectSelection: gridSelectionState.clearObjectSelection,
    selectedToken: tokenSelectionState.selectedToken,
    selectedTokensList: tokenSelectionState.selectedTokensList,
    clearTokenSelection: tokenSelectionState.clearTokenSelection,
    showToast: feedbackState.showToast,
    promptUser,
    confirmUser,
    updateObjectById: sceneState.updateObjectById,
    updateTokenById: tokenSelectionState.updateTokenById,
    maps: sceneState.maps,
    setMaps: sceneState.setMaps,
    objects: sceneState.objects,
    setObjects: sceneState.setObjects,
    tokens: tokenSelectionState.tokens,
    setTokens: tokenSelectionState.setTokens,
    gridSettings: gridSettingsState.gridSettings,
    setGridSettings: gridSettingsState.setGridSettings,
    tileSize: tileState.tileSize,
    setTileSize,
    engine,
    setEngine,
    interactionMode: layerState.interactionMode,
    setInteractionMode: layerState.setInteractionMode,
    setZoomToolActive: zoomState.setZoomToolActive,
    setPanToolActive: zoomState.setPanToolActive,
    setCanvasColor: layerState.setCanvasColor,
    canvasRefs: canvasRefsState.canvasRefs,
    canvasColor: layerState.canvasColor,
    placeTiles: sceneState.placeTiles,
    addObject: sceneState.addObject,
    eraseObjectAt: sceneState.eraseObjectAt,
    moveObject: sceneState.moveObject,
    removeObjectById: sceneState.removeObjectById,
    removeTokenById: tokenSelectionState.removeTokenById,
    addToken: tokenSelectionState.addToken,
    moveToken: tokenSelectionState.moveToken,
    projectName: () => projectNameRef.current,
  });

  const { setCreatorOpen, setEditingAsset, editingAsset, updateAssetById } = legacyAssetWorkflow;

  const closeAssetCreator = useCallback(() => {
    setCreatorOpen(false);
    setEditingAsset(null);
  }, [setCreatorOpen, setEditingAsset]);

  const handleAssetUpdate = useCallback(
    (updated) => {
      if (!editingAsset) return;
      updateAssetById(editingAsset.id, updated);
    },
    [editingAsset, updateAssetById]
  );

  const historyState = useLegacyHistory({
    undoStack: undoRedoState.undoStack,
    setUndoStack: undoRedoState.setUndoStack,
    redoStack: undoRedoState.redoStack,
    setRedoStack: undoRedoState.setRedoStack,
    maps: sceneState.maps,
    setMaps: sceneState.setMaps,
    objects: sceneState.objects,
    setObjects: sceneState.setObjects,
    tokens: tokenSelectionState.tokens,
    setTokens: tokenSelectionState.setTokens,
    assets: legacyAssetWorkflow.assets,
    setAssets: legacyAssetWorkflow.setAssets,
    gridSettings: gridSettingsState.gridSettings,
    setGridSettings: gridSettingsState.setGridSettings,
    brushSize: legacyAssetWorkflow.brushSize,
    setBrushSize: legacyAssetWorkflow.setBrushSize,
    canvasOpacity: canvasDisplayState.canvasOpacity,
    setCanvasOpacity: canvasDisplayState.setCanvasOpacity,
    canvasSpacing: canvasDisplayState.canvasSpacing,
    setCanvasSpacing: canvasDisplayState.setCanvasSpacing,
    canvasBlendMode: canvasDisplayState.canvasBlendMode,
    setCanvasBlendMode: canvasDisplayState.setCanvasBlendMode,
    canvasSmoothing: canvasDisplayState.canvasSmoothing,
    setCanvasSmoothing: canvasDisplayState.setCanvasSmoothing,
    naturalSettings: canvasDisplayState.naturalSettings,
    setNaturalSettings: canvasDisplayState.setNaturalSettings,
    tileSize: tileState.tileSize,
    setTileSize,
    scrollRef: layoutRefs.scrollRef,
    canvasRefs: canvasRefsState.canvasRefs,
    layers: layerList,
    setLayers: layerState.setLayers,
    setCurrentLayer: layerState.setCurrentLayer,
    layerVisibility: layerVisibilityState.layerVisibility,
    setLayerVisibility: layerVisibilityState.setLayerVisibility,
    currentLayer: layerState.currentLayer,
    showToast: feedbackState.showToast,
    selectedObjsList: gridSelectionState.selectedObjsList,
    selectedTokensList: tokenSelectionState.selectedTokensList,
    removeObjectById: sceneState.removeObjectById,
    removeTokenById: tokenSelectionState.removeTokenById,
    clearObjectSelection: gridSelectionState.clearObjectSelection,
    clearTokenSelection: tokenSelectionState.clearTokenSelection,
  });

  useSelectionSettingsPersistence({
    gridSettings: gridSettingsState.gridSettings,
    selectedObjsList: gridSelectionState.selectedObjsList,
    selectedTokensList: tokenSelectionState.selectedTokensList,
    currentLayer: layerState.currentLayer,
    updateObjectById: sceneState.updateObjectById,
    updateTokenById: tokenSelectionState.updateTokenById,
    onBeginObjectStroke: historyState.onBeginObjectStroke,
    onBeginTokenStroke: historyState.onBeginTokenStroke,
  });

  const projectLoadingState = useLegacyProjectLoading({
    isAssetsFolderConfigured,
    setNeedsAssetsFolder: legacyAssetWorkflow.setNeedsAssetsFolder,
    setAssetsFolderDialogOpen: legacyAssetWorkflow.setAssetsFolderDialogOpen,
    showToast: feedbackState.showToast,
    listMaps,
    loadProjectById,
    setRowsInput: sceneState.setRowsInput,
    setColsInput: sceneState.setColsInput,
    setMaps: sceneState.setMaps,
    setObjects: sceneState.setObjects,
    setTokens: tokenSelectionState.setTokens,
    setAssets: legacyAssetWorkflow.setAssets,
    setSelectedAssetId: legacyAssetWorkflow.setSelectedAssetId,
    projectNameRef,
    canvasRefs: canvasRefsState.canvasRefs,
    confirmUser,
    deleteMap,
    setLayers: layerState.setLayers,
    setCurrentLayer: layerState.setCurrentLayer,
    setLayerVisibility: layerVisibilityState.setLayerVisibility,
  });

  const projectSavingState = useLegacyProjectSaving({
    layers: layerState.layers,
    isAssetsFolderConfigured,
    showToast: feedbackState.showToast,
    setNeedsAssetsFolder: legacyAssetWorkflow.setNeedsAssetsFolder,
    setAssetsFolderDialogOpen: legacyAssetWorkflow.setAssetsFolderDialogOpen,
    hasCurrentProjectDir,
    promptUser,
    saveProjectManager,
    saveProjectAsManager,
    loadAssetsFromStoredParent,
    setAssets: legacyAssetWorkflow.setAssets,
    setSelectedAssetId: legacyAssetWorkflow.setSelectedAssetId,
    setUndoStack: undoRedoState.setUndoStack,
    setRedoStack: undoRedoState.setRedoStack,
    projectNameRef,
    canvasRefs: canvasRefsState.canvasRefs,
    rows: sceneState.rows,
    cols: sceneState.cols,
    tileSize: tileState.tileSize,
    maps: sceneState.maps,
    objects: sceneState.objects,
    tokens: tokenSelectionState.tokens,
    assets: legacyAssetWorkflow.assets,
    currentLayer: layerState.currentLayer,
    brushSize: legacyAssetWorkflow.brushSize,
    gridSettings: gridSettingsState.gridSettings,
    engine,
    layerVisibility: layerVisibilityState.layerVisibility,
    tokensVisible: tokenSelectionState.tokensVisible,
    tokenHUDVisible: tokenSelectionState.tokenHUDVisible,
    tokenHUDShowInitiative: tokenSelectionState.tokenHUDShowInitiative,
    assetGroup: legacyAssetWorkflow.assetGroup,
    showGridLines,
    canvasOpacity: canvasDisplayState.canvasOpacity,
    canvasSpacing: canvasDisplayState.canvasSpacing,
    canvasBlendMode: canvasDisplayState.canvasBlendMode,
    canvasSmoothing: canvasDisplayState.canvasSmoothing,
    naturalSettings: canvasDisplayState.naturalSettings,
  });

  return {
    legacyAssetWorkflow,
    closeAssetCreator,
    handleAssetUpdate,
    historyState,
    projectLoadingState,
    projectSavingState,
  };
}

export default useLegacyProjectModules;
