export const LEGACY_MAP_BUILDER_Z_INDEX_CLASSES = {
  TOOL_HUD_OVERLAY: "z-[10015]",
  RIGHT_ASSETS_OVERLAY: "z-[10014]",
  RIGHT_ASSETS_COLLAPSED_TABS: "z-[10019]",
};

export default LEGACY_MAP_BUILDER_Z_INDEX_CLASSES;
