export function createLegacyMapBuilderViewModel(state) {
  const {
    undo,
    redo,
    saveProject,
    saveProjectAs,
    openLoadModal,
    mapsMenuOpen,
    toggleMapsMenu,
    openMapSizeModal,
    needsAssetsFolder,
    promptChooseAssetsFolder,
    toasts,
    promptState,
    confirmState,
    promptInputRef,
    submitPrompt,
    cancelPrompt,
    approveConfirm,
    cancelConfirm,
    creatorOpen,
    editingAsset,
    creatorKind,
    selectedAsset,
    handleCreatorCreate,
    handleAssetUpdate,
    closeAssetCreator,
    loadModalOpen,
    mapsList,
    closeLoadModal,
    handleLoadMapFromList,
    handleDeleteMapFromList,
    panToolActive,
    zoomToolActive,
    engine,
    interactionMode,
    assetGroup,
    currentLayer,
    layerVisibility,
    selectedObj,
    selectedObjsList,
    selectedToken,
    selectedTokensList,
    assets,
    gridSettings,
    setGridSettings,
    naturalSettings,
    setNaturalSettings,
    brushSize,
    setBrushSize,
    canvasOpacity,
    setCanvasOpacity,
    canvasSpacing,
    setCanvasSpacing,
    canvasBlendMode,
    setCanvasBlendMode,
    canvasSmoothing,
    setCanvasSmoothing,
    tileSize,
    snapshotSettings,
    regenerateLabelInstance,
    updateTokenById,
    tokenHUDVisible,
    setTokenHUDVisible,
    tokenHUDShowInitiative,
    setTokenHUDShowInitiative,
    setCurrentLayer,
    toggleLayerVisibility,
    tokensVisible,
    setTokensVisible,
    showGridLines,
    setShowGridLines,
    setTileSize,
    setInteractionMode,
    setZoomToolActive,
    setPanToolActive,
    isErasing,
    setIsErasing,
    setEngine,
    openSaveSelectionDialog,
    deleteCurrentSelection,
    undoStack,
    redoStack,
    maps,
    objects,
    gridContentRef,
    scrollRef,
    canvasRefs,
    placeTiles,
    addObject,
    eraseObjectAt,
    moveObject,
    removeObjectById,
    updateObjectById,
    handleSelectionChange,
    tokens,
    addToken,
    moveToken,
    removeTokenById,
    handleTokenSelectionChange,
    mapSizeModalOpen,
    rowsInput,
    colsInput,
    handleChangeRows,
    handleChangeCols,
    closeMapSizeModal,
    applyMapSize,
    setAssetGroup,
    showAssetKindMenu,
    setShowAssetKindMenu,
    showAssetPreviews,
    setShowAssetPreviews,
    selectedAssetId,
    selectAsset,
    setCreatorOpen,
    setEditingAsset,
    setAssets,
    setSelectedAssetId,
    assetStamp,
    setAssetStamp,
    saveDialogOpen,
    closeSaveSelectionDialog,
    saveSelectionAsAsset,
    saveMultipleObjectsAsNaturalGroup,
    saveMultipleObjectsAsMergedImage,
    saveSelectedTokenAsAsset,
    saveSelectedTokensAsGroup,
    rows,
    cols,
    layerBarHeight,
    fixedBarTop,
    fixedBarLeft,
    fixedBarWidth,
    overlayTop,
    overlayLeft,
    overlayCenter,
    layerBarWrapRef,
    showToast,
    confirmUser,
    handleZoomToRect,
    onBeginTileStroke,
    onBeginCanvasStroke,
    onBeginObjectStroke,
    onBeginTokenStroke,
    canvasColor,
    openCreator,
  } = state;

  const assetsFolderBannerProps = {
    needsAssetsFolder,
    onChooseFolder: promptChooseAssetsFolder,
  };

  const feedbackLayerProps = {
    toasts,
    promptState,
    confirmState,
    promptInputRef,
    onPromptSubmit: submitPrompt,
    onPromptCancel: cancelPrompt,
    onConfirmApprove: approveConfirm,
    onConfirmCancel: cancelConfirm,
  };

  const assetCreatorModalProps = {
    open: creatorOpen,
    editingAsset,
    creatorKind,
    selectedAsset,
    onClose: closeAssetCreator,
    onCreate: handleCreatorCreate,
    onUpdate: handleAssetUpdate,
  };

  const loadMapsModalProps = {
    open: loadModalOpen,
    mapsList,
    onClose: closeLoadModal,
    onOpenMap: handleLoadMapFromList,
    onDeleteMap: handleDeleteMapFromList,
  };

  const legacySettingsPanelProps = {
    panToolActive,
    zoomToolActive,
    engine,
    interactionMode,
    assetGroup,
    selectedAsset,
    currentLayer,
    layerVisibility,
    selectedObj,
    selectedObjsList,
    selectedToken,
    selectedTokensList,
    assets,
    gridSettings,
    setGridSettings,
    naturalSettings,
    setNaturalSettings,
    brushSize,
    setBrushSize,
    canvasOpacity,
    setCanvasOpacity,
    canvasSpacing,
    setCanvasSpacing,
    canvasBlendMode,
    setCanvasBlendMode,
    canvasSmoothing,
    setCanvasSmoothing,
    tileSize,
    snapshotSettings,
    regenerateLabelInstance,
    updateTokenById,
    tokenHUDVisible,
    setTokenHUDVisible,
    tokenHUDShowInitiative,
    setTokenHUDShowInitiative,
  };

  const layerBarProps = {
    currentLayer,
    setCurrentLayer,
    layerVisibility,
    toggleLayerVisibility,
    tokensVisible,
    setTokensVisible,
    showGridLines,
    setShowGridLines,
    tileSize,
    setTileSize,
  };

  const toolbarProps = {
    interactionMode,
    zoomToolActive,
    panToolActive,
    setInteractionMode,
    setZoomToolActive,
    setPanToolActive,
    isErasing,
    setIsErasing,
    engine,
    setEngine,
    assetGroup,
    canActOnSelection:
      (selectedObjsList?.length || 0) > 0 || (selectedTokensList?.length || 0) > 0,
    onSaveSelection: openSaveSelectionDialog,
    onDeleteSelection: deleteCurrentSelection,
  };

  const historyControls = {
    undo,
    redo,
    undoStack,
    redoStack,
  };

  const gridProps = {
    maps,
    objects,
    assets,
    engine,
    selectedAsset,
    gridSettings,
    stampSettings: assetStamp,
    setGridSettings,
    brushSize,
    canvasOpacity,
    canvasColor,
    canvasSpacing,
    canvasBlendMode,
    canvasSmoothing,
    naturalSettings,
    isErasing,
    interactionMode,
    tileSize,
    scrollRef,
    contentRef: gridContentRef,
    canvasRefs,
    currentLayer,
    layerVisibility,
    tokensVisible,
    tokenHUDVisible,
    tokenHUDShowInitiative,
    assetGroup,
    showGridLines,
    zoomToolActive,
    panToolActive,
    onZoomToolRect: handleZoomToRect,
    onBeginTileStroke,
    onBeginCanvasStroke,
    onBeginObjectStroke,
    onBeginTokenStroke,
    placeTiles,
    addObject,
    eraseObjectAt,
    moveObject,
    removeObjectById,
    updateObjectById,
    onSelectionChange: handleSelectionChange,
    tokens,
    addToken,
    moveToken,
    removeTokenById,
    updateTokenById,
    onTokenSelectionChange: handleTokenSelectionChange,
  };

  const mapSizeModalProps = {
    open: mapSizeModalOpen,
    rowsValue: rowsInput,
    colsValue: colsInput,
    onChangeRows: handleChangeRows,
    onChangeCols: handleChangeCols,
    onCancel: closeMapSizeModal,
    onApply: applyMapSize,
  };

  const bottomAssetsDrawerProps = {
    assetPanelProps: {
      assetGroup,
      setAssetGroup,
      showAssetKindMenu,
      setShowAssetKindMenu,
      showAssetPreviews,
      setShowAssetPreviews,
      assets,
      selectedAssetId,
      selectedAsset,
      selectAsset,
      tokens,
      objects,
      creatorOpen,
      creatorKind,
      editingAsset,
      openCreator,
      setCreatorOpen,
      setEditingAsset,
      handleCreatorCreate,
      updateAssetById,
      setAssets,
      setSelectedAssetId,
      alertFn: (message) => showToast(message, "warning", 3500),
      confirmFn: (message) => confirmUser(message),
    },
    initialHeight: 90,
    minHeight: 0,
    maxHeightPct: 0.7,
    assetStamp,
    setAssetStamp,
    naturalSettings,
    setNaturalSettings,
  };

  const saveSelectionDialogProps = {
    open: saveDialogOpen,
    onClose: closeSaveSelectionDialog,
    selectedObjsList,
    selectedTokensList,
    saveSelectionAsAsset,
    saveMultipleObjectsAsNaturalGroup,
    saveMultipleObjectsAsMergedImage,
    saveSelectedTokenAsAsset,
    saveSelectedTokensAsGroup,
  };

  const headerProps = {
    onUndo: undo,
    onRedo: redo,
    onSave: saveProject,
    onSaveAs: saveProjectAs,
    onLoad: openLoadModal,
    showSaveWords: mapsMenuOpen,
    mapsMenuOpen,
    onToggleMaps: toggleMapsMenu,
    onOpenMapSize: openMapSizeModal,
  };

  return {
    headerProps,
    assetsFolderBannerProps,
    feedbackLayerProps,
    assetCreatorModalProps,
    loadMapsModalProps,
    legacySettingsPanelProps,
    layout: {
      scrollRef,
      gridContentRef,
      layerBarWrapRef,
      layerBarHeight,
      fixedBarTop,
      fixedBarLeft,
      fixedBarWidth,
      overlayTop,
      overlayLeft,
      overlayCenter,
    },
    layerBarProps,
    toolbarProps,
    historyControls,
    gridProps,
    mapSizeModalProps,
    bottomAssetsDrawerProps,
    saveSelectionDialogProps,
  };
}

export default createLegacyMapBuilderViewModel;
