import { useLegacySceneComposition } from "./composers/useLegacySceneComposition.js";
import { useLegacyProjectModules } from "./composers/useLegacyProjectModules.js";

export function useLegacyMapBuilderState() {
  const sceneComposition = useLegacySceneComposition();
  const projectModules = useLegacyProjectModules(sceneComposition);

  const {
    projectNameRef,
    layerState,
    sceneState,
    gridSettingsState,
    gridSelectionState,
    tokenSelectionState,
    saveSelectionDialogState,
    menuState,
    mapSizeDialogState,
    canvasRefsState,
    layoutRefs,
    tileState,
    setTileSize,
    undoRedoState,
    feedbackState,
    promptUser,
    confirmUser,
    layoutState,
    zoomState,
    layerVisibilityState,
    showGridLines,
    setShowGridLines,
    engine,
    setEngine,
    clamp,
    snap,
    handleZoomToRect,
    zoomToFit,
    canvasDisplayState,
    handleChangeRows,
    handleChangeCols,
    applyMapSize,
    addLayerWithHistory,
    removeLayerWithHistory,
    renameLayerWithHistory,
    reorderLayerWithHistory,
  } = sceneComposition;

  const {
    legacyAssetWorkflow,
    closeAssetCreator,
    handleAssetUpdate,
    historyState,
    projectLoadingState,
    projectSavingState,
    activeStorageBackend,
    refreshStorageBackend,
    exportProject,
    clearProjectCaches,
  } = projectModules;

  return {
    projectNameRef,
    ...layerState,
    addLayer: addLayerWithHistory,
    removeLayer: removeLayerWithHistory,
    renameLayer: renameLayerWithHistory,
    reorderLayer: reorderLayerWithHistory,
    ...sceneState,
    ...gridSettingsState,
    ...gridSelectionState,
    ...tokenSelectionState,
    ...saveSelectionDialogState,
    ...menuState,
    ...mapSizeDialogState,
    ...canvasRefsState,
    ...layoutRefs,
    ...tileState,
    setTileSize,
    ...undoRedoState,
    ...feedbackState,
    promptUser,
    confirmUser,
    ...layoutState,
    ...zoomState,
    ...layerVisibilityState,
    showGridLines,
    setShowGridLines,
    engine,
    setEngine,
    clamp,
    snap,
    handleZoomToRect,
    zoomToFit,
    ...canvasDisplayState,
    ...legacyAssetWorkflow,
    closeAssetCreator,
    handleAssetUpdate,
    ...historyState,
    ...projectLoadingState,
    ...projectSavingState,
    activeStorageBackend,
    refreshStorageBackend,
    exportProject,
    clearProjectCaches,
    handleChangeRows,
    handleChangeCols,
    applyMapSize,
  };
}

export default useLegacyMapBuilderState;
